---
title: "Chapter_3"
author: "Zoe"
date: "2025-09-10"
output: html_document
---

### Getting Graphic

------------------------------------------------------------------------

#### Histograms

```{r}
library(datasets)
```

```{r}
head(airquality)
```

```{r}
hist(airquality$Temp)
```

```{r}
hist(airquality$Temp,xlab="Temperature (Degrees
Fahrenheit)",main="Temperatures in New York City May 1 - September 30, 1973")
```

#### Density plots

```{r}
hist(
  airquality$Temp,
  xlab = "Temperature (Degrees Fahrenheit)",
  main = "Temperatures in New York City May 1 - September 30, 1973",
  probability = TRUE
)

lines(density(airquality$Temp), col = "blue", lwd = 2)
```

#### Bar plots

```{r}
library(MASS)
```

```{r}
head(Cars93[1:3])
```

```{r}
table(Cars93$Type)
```

```{r}
barplot(table(Cars93$Type))
```

```{r}
barplot(table(Cars93$Type),ylim=c(0,25),xlab="Type", ylab="Frequency", axis.lty="solid",space=.5)
```

```{r}
library(dplyr)
```

```{r}
USA.Cars93 <- filter(Cars93,Origin == "USA")
```

#### Grouping the bars

```{r}
females <- HairEyeColor[,,2]
```

```{r}
females
```
