### Working with Packages

------------------------------------------------------------------------

#### Installing Packages

```{r}
library("datasets", lib.loc="C:/Program Files/R/R-3.4.0/library")
```

```{r}
library(MASS)
```

```{r}
library(tidyr)
```

#### Examining Data

Heads and tails

```{r}
head(airquality)
```

```{r}
tail(airquality)
```

Missing data

```{r}
mean(airquality$Ozone)
```

```{r}
mean(airquality$Ozone, na.rm=TRUE)
```

Subsets

```{r}
Month.Day.Ozone <- subset(airquality, select = c(Month,Day,Ozone))
```

```{r}
head(Month.Day.Ozone)
```

```{r}
August.Ozone <- subset(airquality, Month == 8, select = c(Month,Day,Ozone))
```

```{r}
head(August.Ozone)
```

#### R Formulas

```{r}
analysis <- lm(Temp ~ Month, data=airquality)
```

```{r}
summary(analysis)
```

```{r}
plot(airquality)
```

```{r}
s <- summary(analysis)
```

```{r}
s$coefficients[2,1]
```

#### Exploring the tidyverse

```{r}
aq.no.missing <-drop_na(airquality)
```

```{r}
head(aq.no.missing)
```

```{r}
space.revenues <- tribble(
  ~`1990`, ~`1991`, ~`1992`, ~`1993`, ~`1994`,
  1000, 1300, 1300, 1100, 1400,
   800, 1200, 1500, 1850, 2330,
   860, 1300, 1400, 1600, 1970,
   570,  380,  450,  465,  580,
   155,  190,  210,  250,  300
)

rownames(space.revenues) <- c(
  "Commercial Satellites Delivered",
  "Satellite Services",
  "Satellite Ground Equipment",
  "Commercial Launches",
  "Remote Sensing Data"
)
```

```{r}
space.revenues
```

```{r}
space.revenues["Satellite Services",2]
```

```{r}
space.revenues[2,2]
```

```{r}
library(tibble)
```

```{r}
revenues.industry <- rownames_to_column(space.revenues, var="Industry")
```

```{r}
revenues.industry
```

```{r}
library(dplyr)
```

```{r}
long.revenues <- revenues.industry %>%
  pivot_longer(
    cols = -Industry,            # all columns except Industry
    names_to = "Year",           # column names ("1990", "1991", …) become Year
    values_to = "Million_Dollars" # values go into this column
  )
```

```{r}
long.revenues
```

```{r}
long.revenues <- gather(revenues.industry,Year,Million_Dollars,2:6)
```

```{r}
long.revenues
```

```{r}
spread(long.revenues,Year,Million_Dollars)
```

```{r}
filter(long.revenues,Industry == "Satellite Services")
```

```{r}
airquality %>%
  filter(Day == 1)
```
